version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=4000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - FRONTEND_URL=https://matteosalvatore.pe
      - CULQI_PUBLIC_KEY=${CULQI_PUBLIC_KEY}
      - CULQI_PRIVATE_KEY=${CULQI_PRIVATE_KEY}

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: https://matteosalvatore.pe/api
        NEXT_PUBLIC_CULQI_PUBLIC_KEY: ${NEXT_PUBLIC_CULQI_PUBLIC_KEY}
        NEXT_PUBLIC_SUPABASE_URL: ${SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    restart: always
    ports:
      - "8010:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://matteosalvatore.pe/api
      - NEXT_PUBLIC_CULQI_PUBLIC_KEY=${NEXT_PUBLIC_CULQI_PUBLIC_KEY}
